//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public int Block_ID { get; set; }
        public string Block_key { get; set; }
        public string Data { get; set; }
        public string Code { get; set; }
        public string Prev_ID { get; set; }
        public string Network { get; set; }
    }
}
